config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    # Django Admin
    url(r'^admin/', include(admin.site.urls)),

    # Core urls
    url(r'^', include("ulpa.core.urls", namespace="core")),

    # User management
    url(r'^users/', include("ulpa.users.urls", namespace="users")),

    # Language urls
    url(r'^languages/', include("ulpa.languages.urls", namespace="languages")),

    # Subject urls
    url(r'^subjects/', include("ulpa.subjects.urls", namespace="subjects")),

    # University urls
    url(r'^universities/', include("ulpa.universities.urls", namespace="universities")),

    # FAQ url
    url(r'^faqs/', include("ulpa.faqs.urls", namespace="faqs")),

    # Robust Email
    url(r'^email/', include("robust_email.urls")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', 'django.views.defaults.bad_request'),
        url(r'^403/$', 'django.views.defaults.permission_denied'),
        url(r'^404/$', 'django.views.defaults.page_not_found'),
        url(r'^500/$', 'django.views.defaults.server_error'),
    ]

robust_email/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import *

from . import views

MESSAGE_ID_PATTERN = r'(?P<message_id>\d+)a(?P<token>.+)'

urlpatterns = [
    url(r'view/%s/$' % MESSAGE_ID_PATTERN, views.view_email, name='view_email'),
    ]

ulpa/core/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for home
    url(r'^$', views.home, name='home'),
    url(r'^setup/$', views.setup, name="setup"),
    url(r'^force_500/$', views.force_500, name="force_500"),
    url(r'^health_check/$', views.health_check, name='health_check'),
    url(r'^about/$', views.about, name="about"),
    url(r'^contact/$', views.contact, name="contact"),
    url(r'^what-languages-can-i-study/$', views.what_languages_can_i_study,
        name="what-languages-can-i-study"),
    url(r'^why-study-languages/$', views.why_study_languages,
        name="why-study-languages"),
    url(r'^can-study-at-university-other-than-own/$', views.can_study_at_uni_other_than_own,
        name="can-study-at-university-other-than-own"),
    url(r'^where-can-study-indigenous-languages/$', views.where_can_study_indigenous_languages,
        name="where-can-study-indigenous-languages"),
    url(r'^google0181146fe649f777/$', views.google_verification, name="google0181146fe649f777"),
    url(r'^url-check/$', views.url_check, name="url-check"),
    url(r'^url-check-results/$', views.url_check_results, name="url-check-results"),
    url(r'^sitemap/$', views.sitemap, name="sitemap"),
]

ulpa/faqs/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for home
    url(r'^$', views.faqs, name='faqs'),
]

ulpa/languages/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^bulk_upload/(?P<bulk_upload_id>\d+)/confirm/', views.languages_confirm_bulk_upload, name='languages-confirm-bulk-upload'),
    url(r'^bulk_upload/', views.languages_bulk_upload, name='languages-bulk-upload'),
    url(r'^search/', views.language_search, name='language-search'),
    url(r'^individual/(?P<language>[-\w]+)$', views.individual_language, name='individual-language'),
    url(r'^category/(?P<category>[-\w]+)$', views.category_language, name='category-language'),
    url(r'^list_universities/', views.list_universities, name='list-universities'),
    url(r'^list_potential_subjects/', views.list_potential_subjects, name='list-potential-subjects'),
]

ulpa/subjects/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^bulk_upload/(?P<bulk_upload_id>\d+)/confirm/', views.subjects_confirm_bulk_upload, name='subjects-confirm-bulk-upload'),
    url(r'^bulk_upload/', views.subjects_bulk_upload, name='subjects-bulk-upload'),
    url(r'^search_results/', views.subject_search_results, name='subject-search-results'),
    url(r'^printable_search_results/', views.printable_subject_search_results, name='printable-subject-search-results'),
]

ulpa/universities/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^bulk_upload/(?P<bulk_upload_id>\d+)/confirm/', views.universities_confirm_bulk_upload, name='universities-confirm-bulk-upload'),
    url(r'^bulk_upload/', views.universities_bulk_upload, name='universities-bulk-upload'),
    url(r'^search/', views.university_search, name='university-search'),
    url(r'^list_languages/', views.list_languages, name='list-languages'),
    url(r'^list_potential_subjects/', views.list_potential_subjects, name='list-potential-subjects'),
    url(r'^list_potential_languages/', views.list_potential_languages, name='list-potential-languages'),
]

ulpa/users/forms.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django import forms

from .models import User


class UserForm(forms.ModelForm):

    class Meta:
        # Set this form to use the User model.
        model = User

        # Constrain the UserForm to just these fields.
        fields = ("first_name", "last_name")

ulpa/core/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.shortcuts import render, redirect

from ulpa.core.forms import LanguageSearchForm, ContactForm, URLCheckForm
from ulpa.core.emails import contact_form_sent_handler
from ulpa.languages.models import Language, LanguageCategory
from ulpa.subjects.models import check_url as check_subject_urls
from ulpa.universities.models import University, check_url as check_university_urls
from ulpa.users.models import User

def setup(request):
    """
    Performs initial site setup
    """
    existing_admin_users = User.objects.filter(is_superuser=True)

    if not existing_admin_users:
        user = User(username='admin', email='evan.brumley@wspdigital.com')

        user.set_password('123')
        
        user.is_superuser = True
        user.is_staff = True
        
        user.save()
    else:
        user = None

    context = {
        'user': user,
    }

    return redirect('core:home')


def force_500(request):
    """
    For testing exception handling
    """
    if request.user.is_superuser:
        raise Exception("Test Exception")
    else:
        return redirect('core:home')


def google_verification(request):
    """
    For Googe Seach Console integration
    """
    template = "google_verification.html"

    context = {
    }

    if request.user.is_superuser:
        return render(request, template, context)
    else:
        return redirect('core:home')


def home(request):

    template = "core/home.html"

    context = {
    }

    return render(request, template, context)


def about(request):

    template = "core/about.html"

    context = {
    }

    return render(request, template, context)


def contact(request):

    template = "core/contact.html"

    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            contact_form_sent_handler(form)
            messages.success(request, "Message sent successfully")
            return redirect('core:home')
            # except Exception, e:
            #     messages.error(request, "An error occured and the message has not sent successfully. Please try again later. %s" % e)

    context = {
        'form': form,
    }

    return render(request, template, context)


def faq(request):

    template = "core/faq.html"

    context = {
    }

    return render(request, template, context)


def what_languages_can_i_study(request):

    template = "core/what_languages_can_i_study.html"

    languages = Language.objects.all()
    language_categories = LanguageCategory.objects.all().order_by('name')

    if request.method == 'POST':

        form = LanguageSearchForm(request.POST)

        if form.is_valid():
            language = form.cleaned_data.get('language')

    else:

        form = LanguageSearchForm()

    context = {
        'languages': languages,
        'language_categories': language_categories,
        'form': form,
    }

    return render(request, template, context)


def why_study_languages(request):

    template = "core/why_study_languages.html"

    languages = Language.objects.all()

    context = {
        'languages': languages,
    }

    return render(request, template, context)


def can_study_at_uni_other_than_own(request):

    template = "core/can_study_at_uni_other_than_own.html"

    # TODO - Needs updating to appropriate content!

    universities = University.objects.all()

    context = {
        'universities': universities,
    }

    return render(request, template, context)


def where_can_study_indigenous_languages(request):
    INDIGENOUS_LANGUAGES_SLUG = 'Australian Indigenous Languages'
    template = "core/where_can_study_indigenous_languages.html"

    universities = University.objects.all()
    indigenous_languages = Language.objects.filter(categories__name=INDIGENOUS_LANGUAGES_SLUG)

    context = {
        'indigenous_languages': indigenous_languages,
    }

    return render(request, template, context)


def health_check(request):
    template = "health_check.xml"

    status = 200

    context = {
        'status': "OK",
        'response_time': 1.1,  # TODO: Figure out wtf is going here
    }

    return render(request, template, context, status=status, content_type="text/xml")

@login_required
def url_check(request):
    template = "url_check.html"
    university_urls = ""
    subject_urls = ""
    results = {}

    if request.method == 'GET':
        form = URLCheckForm()
    else:
        university_urls = check_university_urls()
        subject_urls = check_subject_urls()
        form = URLCheckForm()

    if university_urls:
        results = {
            'universities': university_urls,
            'subjects': subject_urls,
        }

    context = {
        'form': form,
        'results': results,
    }

    return render(request, template, context)

@login_required
def url_check_results(request):
    template = "url_check_results.html"

    context = {

    }

    return render(request, template, context)


def sitemap(request):
    template = "sitemap.xml"

    context = {

    }

    return render(request, template, context)

ulpa/faqs/views.py
from django.shortcuts import render

from .models import FAQCategory


def faqs(request):
    """

    """
    template = "faqs/index.html"

    all_faqs = FAQCategory.objects.all()

    context = {
        'all_faqs': all_faqs,
    }

    return render(request, template, context)

ulpa/languages/views.py
import json
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse

from ulpa.universities.models import University
from ulpa.subjects.models import Subject

from .models import Language, LanguageCategory, LanguageBulkUpload
from .forms import LanguageSearchForm, LanguagesBulkUploadForm


@login_required
def languages_bulk_upload(request):
    """
    Initial page for bulk uploading Subjects within a XLSX file.
    If errors occur with file upload, deals with it here (not
    including parsing errors). Then passes the created bulk_upload
    to the confirm view below
    """
    template = "languages/bulk_upload.html"
    if request.method == 'POST':
        form = LanguagesBulkUploadForm(request.POST, request.FILES)
        if form.is_valid():
            bulk_upload = form.save(commit=False)
            bulk_upload.user = request.user

            bulk_upload.save()

            return redirect('languages:languages-confirm-bulk-upload', bulk_upload.pk)
        else:
            messages.error(request, "There was a problem with your submission,\
                                    please check the form below for errors and\
                                    try again")
    else:
        form = LanguagesBulkUploadForm()

    context = {
        'form': form,
    }

    return render(request, template, context)

@login_required
def languages_confirm_bulk_upload(request, bulk_upload_id):
    """
    Takes the bulk_upload created above and processes the data.
    Deals with errors if they occur, else, lets the user know
    how many subjects were successfully created.
    """

    template = "languages/confirm_bulk_upload.html"

    bulk_upload = get_object_or_404(LanguageBulkUpload, pk=bulk_upload_id)

    if not bulk_upload.is_pending:
        messages.error(request, "Sorry, the bulk upload you were accessing has\
                                 already been actioned. Please re-upload your\
                                 XLSX file.")

    results = bulk_upload.results

    if request.method == "POST":
        if 'submit_confirm' in request.POST and not bulk_upload.errors:
            languages = bulk_upload.process()

            added_languages = languages.get('languages')
            added_categories = languages.get('categories')

            messages.success(request, "%s languages created successfully. %s categories created successfully" % (len(added_languages), len(added_categories)))
            return redirect('core:home')

        elif 'submit_cancel' in request.POST:
            bulk_upload.cancel()
            messages.success(request, "Bulk upload cancelled")
            return redirect('languages-bulk-upload')

    context = {
        'bulk_upload': bulk_upload,
        'results': results,
    }

    return render(request, template, context)


def individual_language(request, *args, **kwargs):

    template = "languages/individual_language.html"

    language = kwargs.get('language')

    individual_language = get_object_or_404(Language, slug__iexact=language)
    subject_universities = Subject.objects.filter(language__slug=language).values_list('university', flat=True).distinct()
    universities_with_language = University.objects.filter(pk__in=subject_universities)

    context = {
        'universities_with_language': universities_with_language,
        'individual_language': individual_language,
    }

    return render(request, template, context)


def category_language(request, *args, **kwargs):

    template = "languages/category_language.html"

    category = kwargs.get('category')

    category_language = get_object_or_404(LanguageCategory, slug__iexact=category)
    individual_languages = Language.objects.filter(categories=category_language)

    context = {
        'category_language': category_language,
        'individual_languages': individual_languages,
    }

    return render(request, template, context)


def language_search(request, *args, **kwargs):

    template = "languages/language_search.html"

    state_choices = Subject.STATE_CHOICES
    states = []
    all_subjects = Subject.objects.all()

    for state in state_choices:
        universities = University.objects.filter(subjects__state=state[0]).distinct()
        states.append((state[0], universities))

    states.sort()
    form = LanguageSearchForm(request.GET or None)

    if form.is_valid():

        form = LanguageSearchForm(request.GET)

    context = {
        'form': form,
        'states': states,
    }

    return render(request, template, context)

def list_potential_subjects(request):
    response_subject = {}
    language_query = []
    all_subjects = Subject.objects.all()
    for var in request.GET:
        languageselected = request.GET.get(var)
        found_subjects = all_subjects.filter(language__name = languageselected)
        response_subject[languageselected] = len(found_subjects)

    return JsonResponse(response_subject, safe=False)


def list_universities(request):
    language_query = []
    response_universities = {}
    all_subjects = Subject.objects.all()
    state_choices = Subject.STATE_CHOICES
    states = []
    response_subjects = {}
    for var in request.GET:
        language = request.GET.get(var)
        language_query.append(language)
      
    available_subjects = Subject.objects.filter(language__name__in=language_query).select_related('university')
    
    for subject in available_subjects:
        if subject.state in response_universities:
            if subject.university.name in response_universities[subject.state]:
                pass
            else:
                response_universities[subject.state] += [subject.university.name]
        else:
            response_universities[subject.state] = [subject.university.name]

    for state in response_universities:
       for university in response_universities[state]:

           found_subjects = all_subjects.filter(language__name__in=language_query, university__name = university)
           if state in response_subjects:
              response_subjects[state] +=[(university,len(found_subjects))]
           else:
              response_subjects[state] = [(university,len(found_subjects))]

    return JsonResponse(response_subjects, safe=False)

ulpa/templates/subjects/bulk_upload.html
{% extends "nav_base.html" %}

{% block title %}
    Subjects bulk upload
{% endblock title %}

{% block nav %}
    {% include "includes/nav.html" with active_tab='bulk-upload' %}
{% endblock nav %}

{% block content %}
{% include 'includes/upload_nav.html' %}
<div class="row">
    <div class="col-xs-12">
        <div class="row">
            <h1 class="col-xs-12">Subject Bulk Upload</h1>
            <p class="col-xs-6 bg-warning text-warning">Please ensure the languages and universities are up to date prior to uploading subjects</p>
        </div>
        <div class="row">
            <form method="post" class="col-xs-6 form-horizontal" action="./" enctype="multipart/form-data" id="add-form">
                {% csrf_token %}
                <div class="bulk-upload">
                    {{form.xlsx_file}}
                </div>
                <input id="upload" type='submit' class="btn btn-default " value="Upload">
            </form>
        </div>
    </div>
</div>
{% endblock %}

ulpa/templates/subjects/printable_search_results.html
{% extends "nav_base.html" %}

{% load staticfiles i18n %}

{% block title %}
    Subject Search Results
{% endblock title %}

{% block content %}


<div class="search-results row">

    <h1 class="col-xs-12">YOUR SEARCH RESULTS</h1>

    {% if subjects %}
        <div class="sort col-xs-12">
            <div class="dropdown">
            </div>
        </div>
    {% endif %}

    {% for subject in subjects %}
        {% include 'subjects/includes/search_results_subject.html' with subject=subject%}
    {% empty %}
        <div class="col-sm-12">
            <h2>No Subjects Found</h2>
        </div>
    {% endfor %}
</div>

</div>

{% endblock %}


{% block extra_scripts %}
<script src="{% static 'js/print-results.js' %}"></script>
{% endblock %}

ulpa/templates/subjects/search_results.html
{% extends "nav_base.html" %}
{% load staticfiles i18n %}
{% load bootstrap_pagination %}

{% block title %}
    Subject Search Results
{% endblock title %}

{% block content %}


<div class="search-results row">

    <h1 class="col-xs-12">YOUR SEARCH RESULTS</h1>

    <div class="search-by-buttons hidden-xs hidden-sm col-sm-12">
        <div class="col-xs-6">
            <a class="btn btn-search-by" href="{% url 'languages:language-search' %}">NEW SEARCH BY LANGUAGE</a>
        </div>
        <div class="col-xs-6">
            <a class="btn btn-search-by" href="{% url 'universities:university-search' %}">NEW SEARCH BY UNIVERSITY</a>
        </div>
    </div>
    <div class="search-by-buttons visible-xs-block visible-sm-block col-xs-12">
        <li class="list-unstyled">
            <a class="btn btn-search-by" href="{% url 'languages:language-search' %}">NEW SEARCH BY LANGUAGE <div class="search-arrow "></div></a>
        </li>
        <li class="list-unstyled">
            <a class="btn btn-search-by" href="{% url 'universities:university-search' %}">NEW SEARCH BY UNIVERSITY <div class="search-arrow "></div></a>
        </li>
    </div>

    
        <div class="sort col-xs-12 ">
            <div class="dropdown col-md-4">
                <button class="btn btn-default dropdown-toggle" type="button" id="sortDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Sort by: {{sort_order|default:"Language"|title}}
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" aria-labelledby="sortDropdown">
                    <li><a href="{% url 'subjects:subject-search-results' %}?{{search_parameters.urlencode}}&amp;sort_by=language">Language</a></li>
                    <li><a href="{% url 'subjects:subject-search-results' %}?{{search_parameters.urlencode}}&amp;sort_by=university">University</a></li>
                </ul>
                <a href="{% url 'subjects:printable-subject-search-results' %}?{{search_parameters.urlencode}}" class="btn btn-default" type="button" id="print" aria-labelledby="printResults" aria-expanded="true" target="_blank">
                    Print View
                </a>
            </div>                
            <div class = "dropdown col-md-offset-4 col-md-4">
                <button class="btn btn-default dropdown-toggle" type="button" id="filterDropdown" data-toggle="collapse" data-target="#filter-collapse" role="tab" href="#filter-collapse">
                    <span class="glyphicon glyphicon-filter">Filter</span>
                </button>
                      <div id="filter-collapse" class="panel-collapse collapse" role="tabpanel" aria-labelledby="filter">
                       <div class = "study-choices"><strong>Study Chioces</strong><br>
                       <label class = "radio-inline" data-toggle="tooltip"  title="study entirely online"><input type="radio" name="study-choice-radio" id ="study-choice-online" value ="online" onclick = "online_disabled()">Online</label>
                       <label class = "radio-inline" data-toggle="tooltip"  title="study on-campus(but don't mind if a small portion is online)"><input type="radio" name="study-choice-radio" id="study-choice-oncampus" value="on-campus" onclick="oncampus_disabled()">On campus</label>
                       </div>
                       <div class = "intensities"><strong>Intensities</strong><br>
                       <label class ="radio-inline" data-toggle="tooltip"  title="do an intensive course (eg. summer school)"><input type="radio" name="intensities-radio" id="intensity-intensive" value="intensive" onclick="showIntensiveSubjects()">Intensive course</label>
                       <label class = "radio-inline" data-toggle="tooltip"  title="study over a regular semester"><input type="radio" name="intensities-radio" id="intensity-regular" value="regular" onclick="showRegularSubjects()">Regular semester</label> 
                       </div>
                      <button type="button" onclick="myFilterFunction()">Filter</button>
                      </div>
             </div>
         </div>
         <div class="sort col-xs-12 ">
            <div class="dropdown col-md-4">
                 {% if study_choices %}
                 <p hidden id="study_choices">{{study_choices}}</p>
                 {% endif %}

                 {% if intensities%}
                 <p hidden id="intensities">{{intensities}}</p>
                 {% endif %}

                 {% if study_choices_disable %}
                 <p hidden id="study_choices_disable">{{study_choices_disable}}</p>
                 {% endif %}

                 {% if intensities_disable %}
                 <p hidden id="intensities_disable">{{intensities_disable}}</p>
                 {% endif %}
               {% if online_subjects %}
               <p name ="onlineInfo" hidden="hidden" id="online_subjects">There are <strong>{{online_subjects}}</strong> online subjects available</p>
               {% endif %}
               {% if oncampus_subjects %}
               <p name ="oncampusInfo" hidden="hidden" id="oncampus_subjects">There are <strong>{{oncampus_subjects}}</strong> subjects available on campus</p>
               {% endif %}
               {% if online_regular_subjects %}
               <p name ="onlineInfo" hidden="hidden" id="online_regular_subjects">There are <strong>{{online_regular_subjects}}</strong> regular subjects available online</p>
               {% endif %}
               {% if oncampus_regular_subjects %}
               <p name = "oncampusInfo" hidden="hidden" id="oncampus_regular_subjects">There are <strong>{{oncampus_regular_subjects}}</strong> regular subjects available on campus</p>
               {% endif %}
               {% if online_intensive_subjects %}
               <p name ="onlineInfo" hidden="hidden" id="online_intensive_subjects">There are <strong>{{online_intensive_subjects}}</strong> intensive subjects available online</p>
               {% endif %}
               {% if oncampus_intensive_subjects %}
               <p name ="oncampusInfo" hidden="hidden"id="oncampus_intensive_subjects">There are <strong>{{oncampus_intensive_subjects}}</strong> intensive subjects available on campus</p>
               {% endif %}
              </div>
          </div>

    {% for subject in subjects %}
        {% include 'subjects/includes/search_results_subject.html' with subject=subject%}
    {% empty %}
        <div class="col-xs-12">
            <h2>No Subjects Found</h2>
        </div>
    {% endfor %}
</div>

    {% if subjects %}

    <div class="row">
        <div class="step-links col-xs-12 visible-xs visible-sm text-center">
            {% bootstrap_paginate subjects range=5 %}
        </div>
        <div class="step-links col-xs-12 hidden-xs hidden-sm text-center">
            {% bootstrap_paginate subjects range=10 %}
        </div>
    </div>

    <div class="new-search visible-xs-block visible-sm-block row">
        <li class="list-unstyled col-xs-12">
            <a class="btn btn-search-by" href="{% url 'languages:language-search' %}">NEW SEARCH BY LANGUAGE <div class="search-arrow "></div></a>
        </li>
        <li class="list-unstyled col-xs-12">
            <a class="btn btn-search-by" href="{% url 'universities:university-search' %}">NEW SEARCH BY UNIVERSITY <div class="search-arrow "></div></a>
        </li>
    </div>
    {% endif %}
{% block extra_scripts %}
     
    <script src="{% static 'js/search_results.js' %}"></script>
{% endblock extra_scripts %}

{% endblock %}