config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    # Django Admin
    url(r'^admin/', include(admin.site.urls)),

    # Core urls
    url(r'^', include("ulpa.core.urls", namespace="core")),

    # User management
    url(r'^users/', include("ulpa.users.urls", namespace="users")),

    # Language urls
    url(r'^languages/', include("ulpa.languages.urls", namespace="languages")),

    # Subject urls
    url(r'^subjects/', include("ulpa.subjects.urls", namespace="subjects")),

    # University urls
    url(r'^universities/', include("ulpa.universities.urls", namespace="universities")),

    # FAQ url
    url(r'^faqs/', include("ulpa.faqs.urls", namespace="faqs")),

    # Robust Email
    url(r'^email/', include("robust_email.urls")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', 'django.views.defaults.bad_request'),
        url(r'^403/$', 'django.views.defaults.permission_denied'),
        url(r'^404/$', 'django.views.defaults.page_not_found'),
        url(r'^500/$', 'django.views.defaults.server_error'),
    ]

robust_email/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import *

from . import views

MESSAGE_ID_PATTERN = r'(?P<message_id>\d+)a(?P<token>.+)'

urlpatterns = [
    url(r'view/%s/$' % MESSAGE_ID_PATTERN, views.view_email, name='view_email'),
    ]

ulpa/core/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for home
    url(r'^$', views.home, name='home'),
    url(r'^setup/$', views.setup, name="setup"),
    url(r'^force_500/$', views.force_500, name="force_500"),
    url(r'^health_check/$', views.health_check, name='health_check'),
    url(r'^about/$', views.about, name="about"),
    url(r'^contact/$', views.contact, name="contact"),
    url(r'^what-languages-can-i-study/$', views.what_languages_can_i_study,
        name="what-languages-can-i-study"),
    url(r'^why-study-languages/$', views.why_study_languages,
        name="why-study-languages"),
    url(r'^can-study-at-university-other-than-own/$', views.can_study_at_uni_other_than_own,
        name="can-study-at-university-other-than-own"),
    url(r'^where-can-study-indigenous-languages/$', views.where_can_study_indigenous_languages,
        name="where-can-study-indigenous-languages"),
    url(r'^google0181146fe649f777/$', views.google_verification, name="google0181146fe649f777"),
    url(r'^url-check/$', views.url_check, name="url-check"),
    url(r'^url-check-results/$', views.url_check_results, name="url-check-results"),
    url(r'^sitemap/$', views.sitemap, name="sitemap"),
]

ulpa/faqs/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for home
    url(r'^$', views.faqs, name='faqs'),
]

ulpa/languages/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^bulk_upload/(?P<bulk_upload_id>\d+)/confirm/', views.languages_confirm_bulk_upload, name='languages-confirm-bulk-upload'),
    url(r'^bulk_upload/', views.languages_bulk_upload, name='languages-bulk-upload'),
    url(r'^search/', views.language_search, name='language-search'),
    url(r'^individual/(?P<language>[-\w]+)$', views.individual_language, name='individual-language'),
    url(r'^category/(?P<category>[-\w]+)$', views.category_language, name='category-language'),
    url(r'^list_universities/', views.list_universities, name='list-universities'),
    url(r'^list_potential_subjects/', views.list_potential_subjects, name='list-potential-subjects'),
]

ulpa/subjects/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^bulk_upload/(?P<bulk_upload_id>\d+)/confirm/', views.subjects_confirm_bulk_upload, name='subjects-confirm-bulk-upload'),
    url(r'^bulk_upload/', views.subjects_bulk_upload, name='subjects-bulk-upload'),
    url(r'^search_results/', views.subject_search_results, name='subject-search-results'),
    url(r'^printable_search_results/', views.printable_subject_search_results, name='printable-subject-search-results'),
]

ulpa/subjects/models.py
"""
Models class for Subjects and SubjectBulkUploads.
Stores the Subject pre and post processing from the XLSX file
uploaded via the "subjects/import.html" page.
"""

from __future__ import unicode_literals, absolute_import
import ssl
# import threading
# import Queue
# import requests
import csv
import time
import httplib
import urllib
import urllib2
from django.core.files import File

from django.db import models

from openpyxl import load_workbook
from select_multiple_field.models import SelectMultipleField

from ulpa.users.models import User

from ulpa.utils.model_helpers import CreatedModifiedMixin


class Subject(CreatedModifiedMixin, models.Model):
    """
    A single Subject, related to universities and languages.

        A University has many Subjects and a Subject
        only exists in one University.

        A Language has many Subjects and a Subject
        only has one language.

    """

    VICTORIA = 'VIC'
    NEW_SOUTH_WALES = 'NSW'
    SOUTH_AUSTRALIA = 'SA'
    QUEENSLAND = 'QLD'
    WESTERN_AUSTRALIA = 'WA'
    TASMANIA = 'TAS'
    AUSTRALIAN_CAPITAL_TERRITORY = 'ACT'
    NORTHERN_TERRITORY = 'NT'

    STATE_CHOICES = (
        (VICTORIA, 'Victoria'),
        (NEW_SOUTH_WALES, 'New South Wales'),
        (SOUTH_AUSTRALIA, 'South Australia'),
        (QUEENSLAND, 'Queensland'),
        (WESTERN_AUSTRALIA, 'Western Australia'),
        (TASMANIA, 'Tasmania'),
        (AUSTRALIAN_CAPITAL_TERRITORY, 'Australian Capital Territory'),
        (NORTHERN_TERRITORY, 'Northern Territory'),
    )

    INTENSIVE = 'I'
    REGULAR = 'R'

    INTENSIVE_TEXT = 'intensive'
    REGULAR_TEXT = 'regular'
    REGULAR_AND_INTENSIVE = 'both'

    INTENSITY_CHOICES = (
        (INTENSIVE_TEXT, 'I want to do an intensive course (eg. summer school)'),
        (REGULAR_TEXT, 'I want to study over a regular semester'),
    )

    FACE_TO_FACE = 'on-campus'
    ONLINE = 'online'
    ALTONLINE = 'on-line'
    BOTH = 'both'

    YES = 'Yes'
    NO = 'No'
    NONE = 'None'

    STUDY_CHOICES = (
        (FACE_TO_FACE, "I want to study on-campus (but don't mind if a small portion is online)"),
        (ONLINE, 'I want to study entirely online'),
    )

    title = models.CharField(
        max_length=256
    )
    code = models.CharField(
        max_length=256
    )
    url = models.URLField(
        blank=True
    )

    university = models.ForeignKey(
        'universities.University',
        related_name='subjects',
        max_length=256
    )

    state = models.CharField(
        max_length=256,
        choices=STATE_CHOICES,
    )

    other_university = models.TextField(
        max_length=512,
        blank=True,
        null=True
    )

    intensity = SelectMultipleField(
        max_length=50,
        choices=INTENSITY_CHOICES,
    )

    language = models.ForeignKey(
        'languages.Language',
        related_name='subjects',
        max_length=256,
    )

    prerequisite = models.TextField(
        max_length=512,
        blank=True,
        null=True
    )

    non_beginner_level_available = models.BooleanField(
        default=False
    )

    next_offered = models.TextField(
        blank=True,
        null=True,
    )

    study_choice = SelectMultipleField(
        max_length=256,
        choices=STUDY_CHOICES
    )

    notes = models.TextField(
        blank=True
    )

    class Meta(object):
        verbose_name = "subject"
        verbose_name_plural = "subjects"
        ordering = ['language', 'title']

    @property
    def states(self):
        states = []

        for state in self.STATE_CHOICES:
            states.append(state)

        return states

    def __unicode__(self):
        return u'%s' % (self.title)


def check_url():
    url_report = {}

    subjects = Subject.objects.all()

    for subject in subjects:
        if subject.url:
            try:
                url_status = urllib2.urlopen(subject.url, timeout=3).getcode()
            except Exception, e:
                url_status = "The following error occured: %s" % e
        else:
          url_status = "No URL Found"


        url_report[subject.title] = {'url_status': url_status}

    return url_report


class SubjectBulkUpload(CreatedModifiedMixin, models.Model):
    MAX_UPLOAD_SIZE = 5*1024*1024  # 5MB
    STATUS_PENDING = 'pending'
    STATUS_PROCESSED = 'processed'
    STATUS_CANCELLED = 'cancelled'

    STATUS_CHOICES = (
        (STATUS_PENDING, 'Pending'),
        (STATUS_PROCESSED, 'Processed'),
        (STATUS_CANCELLED, 'Cancelled'),
    )

    status = models.CharField(max_length=50, choices=STATUS_CHOICES,
                              default=STATUS_PENDING)
    user = models.ForeignKey(User, related_name="subject_bulk_uploads",
                             null=True, blank=True, on_delete=models.SET_NULL)
    xlsx_file = models.FileField(upload_to='subject_bulk_uploads')

    @property
    def is_pending(self):
        return self.status == self.STATUS_PENDING

    @property
    def is_processed(self):
        return self.status == self.STATUS_PROCESSED

    @property
    def is_cancelled(self):
        return self.status == self.STATUS_CANCELLED

    @property
    def errors(self):
        errors = []

        for result in self.results:
            if result['errors']:
                errors.append(result['errors'])

        return errors

    def process(self):
        if self.status != self.STATUS_PENDING:
            return False

        if self.errors:
            return False

        records = self.save_records()

        self.status = self.STATUS_PENDING

        self.save()

        return records

    def save_records(self):
        records = []

        for result in self.results:
            record = result['subject']

            try:
                existing_subject = Subject.objects.get(title=record.title, university=record.university,
                                                       code=record.code, language=record.language)
            except Subject.DoesNotExist:
                existing_subject = None
            except Subject.MultipleObjectsReturned:
                existing_subject = Subject.objects.filter(title=record.title,
                                                          university=record.university,
                                                          code=record.code,
                                                          language=record.language)
                existing_subject = existing_subject[0]

            if existing_subject:
                record.pk = existing_subject.pk
                record.created = existing_subject.created

            if record:
                record.save()
                records.append(record)

        return records

    def cancel(self):
        if self.status != self.STATUS_PENDING:
            return False

        self.status = self.STATUS_CANCELLED
        self.save()

        return True

    @property
    def results(self):
        from .forms import SubjectFormForBulkUpload

        from ulpa.languages.models import Language
        from ulpa.universities.models import University

        if hasattr(self, '_cached_results'):
            return self._cached_results

        results = []

        xlsx_size = self.xlsx_file._get_size()

        if xlsx_size > self.MAX_UPLOAD_SIZE:
            return results

        xlsx_workbook = load_workbook(self.xlsx_file.file)
        xlsx_sheet = xlsx_workbook.get_active_sheet()

        all_languages = Language.objects.all()
        all_languages_list = list(all_languages)
        all_universities = University.objects.all()
        all_universities_list = list(all_universities)

        for index, row in enumerate(xlsx_sheet.rows):
            if index == 0:
                continue

            errors = []

            try:
                subject_title = row[0].value.strip()
                subject_code = row[1].value
                subject_url = row[2].value
                university_name = row[3].value.strip()
                subject_state = row[4].value.strip()
                other_universities = row[5].value
                subject_intensity = row[6].value.strip()
                language_name = row[7].value.strip()
                prerequisite_languages = row[8].value
                non_beginner_level_available = row[9].value
                subject_next_offered = row[10].value
                subject_study_choice = row[11].value.strip()
                subject_notes = row[12].value
            except AttributeError:
                errors.append('Empty row found, please remove and try again')
                continue
            except IndexError:
                errors.append('Too many rows found, please check your data and try again')
                continue

            try:
                language = [language for language in all_languages_list
                            if language.name == language_name]

                if len(language) >= 1:
                    language = language[0]
                else:
                    language = language

            except Language.DoesNotExist:
                language = None
                errors.append("Invalid language")
            except IndexError:
                errors.append("Language not found")

            try:
                university = [university for university in all_universities_list
                              if university.name == university_name]
                university = university[0]
            except University.DoesNotExist:
                university = None
                errors.append("Invalid university")

            raw_data = {
                'language': language_name,
                'university': university_name,
                'state': subject_state,
                'code': subject_code,
                'title': subject_title,
                'next_offered': subject_next_offered,
                'intensity': subject_intensity,

ulpa/core/forms.py
from django import forms


class LanguageSearchForm(forms.Form):
    language = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), label='Language', max_length=100)

EMAIL = 'Email'
PHONE = 'Phone'

contact_choices = (
    (EMAIL, 'Email'),
    (PHONE, 'Phone'),
)


class ContactForm(forms.Form):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    contact_number = forms.CharField(required=False)
    email = forms.EmailField(required=True)
    preferred_contact_method = forms.ChoiceField(choices=contact_choices)
    your_message = forms.CharField(widget=forms.Textarea)

    def clean(self):
        cleaned_data = super(ContactForm, self).clean()

        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')
        contact_number = cleaned_data.get('contact_number')
        email = cleaned_data.get('email')
        preferred_contact_method = cleaned_data.get('preferred_contact_method')


class URLCheckForm(forms.Form):
    run_check = forms.CharField(label='reset', max_length=256, widget=forms.HiddenInput(), initial='GO')

ulpa/faqs/views.py
from django.shortcuts import render

from .models import FAQCategory


def faqs(request):
    """

    """
    template = "faqs/index.html"

    all_faqs = FAQCategory.objects.all()

    context = {
        'all_faqs': all_faqs,
    }

    return render(request, template, context)

ulpa/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from braces.views import LoginRequiredMixin

from .forms import UserForm
from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    form_class = UserForm

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

ulpa/templates/languages/bulk_upload.html
{% extends "nav_base.html" %}

{% block title %}
    Language bulk upload
{% endblock title %}
{% block nav %}
    {% include "includes/nav.html" with active_tab='bulk-upload' %}
{% endblock %}
{% block content %}
{% include 'includes/upload_nav.html' %}

<div class="row">
    <div class="col-xs-12">
        <div class="row">
            <h1 class="col-xs-12">Language Bulk Upload</h1>
        </div>
        <div class="row">
            <form method="post" class="col-xs-6 form-horizontal" action="./" enctype="multipart/form-data" id="add-form">
                {% csrf_token %}
                <div class="bulk-upload">
                    {{form.xlsx_file}}
                </div>
                <input id="upload" type='submit' class="btn btn-default " value="Upload">
            </form>
        </div>
    </div>
</div>
{% endblock %}

ulpa/templates/languages/category_language.html
{% extends "nav_base.html" %}
{% load markdown_deux_tags %}

{% block title %}
    {{category_language.name|title}}
{% endblock title %}

{% block content %}

<div class="row category-language">
	<div class="col-xs-12 col-md-9">
		<h1>{{ category_language.name }}</h1>

		{{ category_language.description|markdown }}

	    <div class="row">
            <div class="search-by-buttons col-xs-12 col-md-6 col-md-offset-3">
                <a class="btn btn-search-by" href="{% url 'subjects:subject-search-results' %}?{% for individual_language in individual_languages %}language={{individual_language.name}}&{% endfor %}">
                    Show me what I can study
                </a>
            </div>
        </div>
    </div>
	<div class="col-md-3">
        <ul id="nav" class="nav hidden-xs hidden-sm">
            <h4>Languages within this category:</h4>
            {% for individual_language in individual_languages %}
                <li class="">
                    <a href="{% url 'languages:individual-language' individual_language.slug %}">{{ individual_language.name }}</a>
                </li>
            {% endfor %}
        </ul>
	</div>
    <div class="col-xs-12">
        <ul id="nav" class="nav visible-xs visible-sm">
            <h4>Languages within this category:</h4>
            {% for individual_language in individual_languages %}
                <li class="">
                    <a href="{% url 'languages:individual-language' individual_language.slug %}">{{ individual_language.name }}</a>
                </li>
            {% endfor %}
        </ul>
	</div>
</div>


{% endblock %}

ulpa/templates/languages/confirm_bulk_upload.html
{% extends "nav_base.html" %}

{% block title %}
    Confirm language bulk upload
{% endblock title %}

{% block content %}

<h2>Confirm Bulk Upload</h2>

    <hr>

    {% if not results %}
        <p>
            We were not able to generate any records from the file you uploaded. Please check your file and try again.
        </p>
    {% else %}
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th width="30px">Row</th>
                    <th width="100%">Data Entered</th>
                    <th width="50px">Status</th>
                    <th>Details</th>
                </tr>
            </thead>
            {% for result in results %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>
                        <table class="table table-condensed table-inner">
                            <tr>
                                <th width="30px">Language Name</th>
                                <td>{{result.raw_data.name}}</td>

                                <th width="30px">Alternative Name</th>
                                <td>{{result.raw_data.alternative_name}}</td>
                            </tr>
                            <tr>
                                <th width="30px">Description</th>
                                <td>{{result.raw_data.description}}</td>

                                <th width="30px">Individual Language Page</th>
                                <td>{{result.raw_data.individual_language}}</td>
                            </tr>
                            <tr>
                                <th width="30px">How Widely Taught</th>
                                <td>{{result.raw_data.how_widely_taught}}</td>

                                <th width="30px">ABS Census Data</th>
                                <td>{{result.raw_data.abs_data}}</td>
                            </tr>
                            <tr>
                                <th width="30px">ABS Classification</th>
                                <td>{{result.raw_data.abs_classification}}</td>
                                <th></th>
                                <td></td>
                            </tr>
                                <th width="30px">Language Category</th>
                                <td>{{result.raw_data.category}}</td>

                                <th width="30px">Language Category Description</th>
                                <td>{{result.raw_data.category_description}}</td>
                            </tr>
                        </table>
                    </td>
                    <td>
                        {% if result.errors %}
                            <p class="text-error"><strong>Error</strong></p>
                        {% elif result.language.warnings %}
                            <p class="text-warning"><strong>Warning</strong></p>
                        {% else %}
                            <p class="text-success"><strong>OK</strong></p>
                        {% endif %}
                    </td>
                    <td>
                        {% if result.errors %}
                            <ul class="details-notification-list">
                                {% for error in result.errors %}
                                    <li><span class="error-icon"></span> {{ error }}</li>
                                {% endfor %}
                            </ul>
                        {% elif result.subject.warnings %}
                            <ul class="details-notification-list">
                                {% for warning in result.language.warnings %}
                                    <li><span class="warning-icon"></span> {{ warning }}</li>
                                {% endfor %}
                            </ul>
                        {% else %}
                            <em>No problems found</em>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% endif %}

    <hr>

    <form action="./" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {% if bulk_upload.errors or not bulk_upload.results %}
            <input type="submit" name="submit_cancel" class="btn btn-large" value="Try Again">
        {% else %}
            <input type="submit" name="submit_cancel" class="btn btn-large" value="Cancel">
            <input type="submit" name="submit_confirm" class="btn btn-large btn-primary" value="Confirm">
        {% endif %}
    </form>

{% endblock %}

ulpa/templates/languages/individual_language.html
{% extends "nav_base.html" %}
{% load markdown_deux_tags %}

{% block title %}
    {{individual_language.name|title}}
{% endblock title %}

{% block content %}

<div class="row individual-language">
	<div class="col-xs-12 col-md-9">
		<h1>{{ individual_language.name }}</h1>
		{{ individual_language.description|markdown }}
	    <div class="row">
            <div class="search-by-buttons col-xs-12 col-md-6 col-md-offset-3">
                <a class="btn btn-search-by" href="{% url 'subjects:subject-search-results' %}?language={{individual_language.name}}">Show me what I can study</a>
            </div>
        </div>
    </div>
	<div class="col-md-3">
        <ul id="nav" class="nav hidden-xs hidden-sm">
            <h4>This language is taught at the following universities:</h4>
            {% for university in universities_with_language %}
                <li class="">
                    {{ university.name }}
                </li>
            {% endfor %}
        </ul>
	</div>
    <div class="col-xs-12">
        <ul id="nav" class="nav visible-xs visible-sm">
            <h4>This language is taught at the following universities:</h4>
            {% for university in universities_with_language %}
                <li class="">
                    {{ university.name }}
                </li>
            {% endfor %}
        </ul>
	</div>
</div>


{% endblock %}

ulpa/templates/languages/language_search.html
{% extends "nav_base.html" %}
{% load staticfiles i18n %}

{% block title %}
    Language Search
{% endblock title %}

{% block content %}

<div class="content row">
    <div class="col-lg-6">
        <h1>
            SEARCH BY LANGUAGE
        </h1>
        <form method="get" class="form-horizontal language-search" action="{% url 'subjects:subject-search-results' %}" id="add-form">
            
            <!--
            Step 1 - Language Selector
            -->

            <div id="step1" class="step">
                <div id="language_input" class="form-group">
                    {{form.language.errors}}
                    <label for="{{form.language.id_for_label}}">
                        Step 1: Choose which language(s) you would like to study (Required)
                    </label>
                    <div class="alert alert-danger hide" id="no-language-error">
                        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                        <span class="sr-only">Error:</span>
                        You must select at least one language
                    </div>
                    {{ form.language }}
                    <div id="available_subjects">
                    </div>
                    <button id="step1-next" class="btn btn-default btn-ulpa next" value="NEXT">NEXT</button>
                </div>
            </div>

            <!--
            Step 2 - University selector
            -->

            <div id="step2" class="step hide">
                <label for="{{form.university.id_for_label}}">
                    Step 2: Choose where you'd like to study (Optional) 
                </label>
                <select multiple="multiple" id="id_university" name="university" tabindex="-1" class="selectized" style="display: none;"></select>
                {% for state in states %}

                    <div class="panel-group" id="state_accordion" role="tablist" aria-multiselectable="true">
                        <div class="panel panel-default">
                            <div class="panel-heading" data-toggle="collapse" data-target="#{{state.0|lower}}-collapse" href="#{{state.0|lower}}-collapse" role="tab" id="{{state.0|lower}}">
                                <div class="custom-checkbox-background"></div>
                                <div class="custom-checkbox-selected hide"></div>
                                <h4 class="panel-title">
                                    <a role="button"  aria-expanded="true" aria-controls="#{{state.0|lower}}-collapse">
                                      {{state.0}}
                                    </a>
                                </h4>
                            </div>
                            <div id="{{state.0|lower}}-collapse" class="panel-collapse collapse" role="tabpanel" aria-labelledby="{{state.0|lower}} universities">
                                <div class="panel-body">


                                </div>
                            </div>
                        </div>
                  </div>
                {% endfor %}
                <div class="form-group">
                    {{form.university.errors}}
                    <button id="step2-back" class="btn btn-default btn-ulpa back" value="BACK">BACK</button>
                    <!--<button id="step2-next" class="btn btn-default btn-ulpa next" value="NEXT">NEXT</button>-->
                    <input id="step2-next" type='submit' class="btn btn-default btn-ulpa next" value="Next">
                </div>
            </div>

            <!--
            Step 3 - How you'd like to study selector
            -->

            <div id="step3" class="step hide">
                <div class="form-group">
                    {{form.study_choice.errors}}
                    <label for="{{form.study_choice.id_for_label}}">
                        Step 3: Choose how you'd like to study (Optional) 
                    </label>
                    {{ form.study_choice }}
                    <button id="step3-back" class="btn btn-default btn-ulpa back" value="BACK">BACK</button>
                    <button id="step3-next" class="btn btn-default btn-ulpa next" value="NEXT">NEXT</button>
                </div>
            </div>

            <!--
            Step 4 - Subject intensity choice
            -->

            <div id="step4" class="step hide">
                <div class="form-group">
                    {{form.intensity.errors}}
                    <label for="{{form.intensity.id_for_label}}">
                        Step 4: Select the intensity of the subject (Optional) 
                    </label>
                    {{ form.intensity }}
                    <button id="step4-back" class="btn btn-default btn-ulpa back" value="BACK">BACK</button>
                    <input id="step4-next" type='submit' class="btn btn-default btn-ulpa next" value="NEXT">
                </div>
            </div>
            {{ form.sort_by }}
        </form>

    </div>
</div>
{% endblock %}

{% block extra_scripts %}

    <script src="{% static 'js/inputs.js' %}"></script>
    <script src="{% static 'js/language-search.js' %}"></script>
{% endblock extra_scripts %}