config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    # Django Admin
    url(r'^admin/', include(admin.site.urls)),

    # Core urls
    url(r'^', include("ulpa.core.urls", namespace="core")),

    # User management
    url(r'^users/', include("ulpa.users.urls", namespace="users")),

    # Language urls
    url(r'^languages/', include("ulpa.languages.urls", namespace="languages")),

    # Subject urls
    url(r'^subjects/', include("ulpa.subjects.urls", namespace="subjects")),

    # University urls
    url(r'^universities/', include("ulpa.universities.urls", namespace="universities")),

    # FAQ url
    url(r'^faqs/', include("ulpa.faqs.urls", namespace="faqs")),

    # Robust Email
    url(r'^email/', include("robust_email.urls")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', 'django.views.defaults.bad_request'),
        url(r'^403/$', 'django.views.defaults.permission_denied'),
        url(r'^404/$', 'django.views.defaults.page_not_found'),
        url(r'^500/$', 'django.views.defaults.server_error'),
    ]

robust_email/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import *

from . import views

MESSAGE_ID_PATTERN = r'(?P<message_id>\d+)a(?P<token>.+)'

urlpatterns = [
    url(r'view/%s/$' % MESSAGE_ID_PATTERN, views.view_email, name='view_email'),
    ]

ulpa/core/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for home
    url(r'^$', views.home, name='home'),
    url(r'^setup/$', views.setup, name="setup"),
    url(r'^force_500/$', views.force_500, name="force_500"),
    url(r'^health_check/$', views.health_check, name='health_check'),
    url(r'^about/$', views.about, name="about"),
    url(r'^contact/$', views.contact, name="contact"),
    url(r'^what-languages-can-i-study/$', views.what_languages_can_i_study,
        name="what-languages-can-i-study"),
    url(r'^why-study-languages/$', views.why_study_languages,
        name="why-study-languages"),
    url(r'^can-study-at-university-other-than-own/$', views.can_study_at_uni_other_than_own,
        name="can-study-at-university-other-than-own"),
    url(r'^where-can-study-indigenous-languages/$', views.where_can_study_indigenous_languages,
        name="where-can-study-indigenous-languages"),
    url(r'^google0181146fe649f777/$', views.google_verification, name="google0181146fe649f777"),
    url(r'^url-check/$', views.url_check, name="url-check"),
    url(r'^url-check-results/$', views.url_check_results, name="url-check-results"),
    url(r'^sitemap/$', views.sitemap, name="sitemap"),
]

ulpa/faqs/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for home
    url(r'^$', views.faqs, name='faqs'),
]

ulpa/languages/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^bulk_upload/(?P<bulk_upload_id>\d+)/confirm/', views.languages_confirm_bulk_upload, name='languages-confirm-bulk-upload'),
    url(r'^bulk_upload/', views.languages_bulk_upload, name='languages-bulk-upload'),
    url(r'^search/', views.language_search, name='language-search'),
    url(r'^individual/(?P<language>[-\w]+)$', views.individual_language, name='individual-language'),
    url(r'^category/(?P<category>[-\w]+)$', views.category_language, name='category-language'),
    url(r'^list_universities/', views.list_universities, name='list-universities'),
    url(r'^list_potential_subjects/', views.list_potential_subjects, name='list-potential-subjects'),
]

ulpa/subjects/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^bulk_upload/(?P<bulk_upload_id>\d+)/confirm/', views.subjects_confirm_bulk_upload, name='subjects-confirm-bulk-upload'),
    url(r'^bulk_upload/', views.subjects_bulk_upload, name='subjects-bulk-upload'),
    url(r'^search_results/', views.subject_search_results, name='subject-search-results'),
    url(r'^printable_search_results/', views.printable_subject_search_results, name='printable-subject-search-results'),
]

ulpa/universities/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^bulk_upload/(?P<bulk_upload_id>\d+)/confirm/', views.universities_confirm_bulk_upload, name='universities-confirm-bulk-upload'),
    url(r'^bulk_upload/', views.universities_bulk_upload, name='universities-bulk-upload'),
    url(r'^search/', views.university_search, name='university-search'),
    url(r'^list_languages/', views.list_languages, name='list-languages'),
    url(r'^list_potential_subjects/', views.list_potential_subjects, name='list-potential-subjects'),
    url(r'^list_potential_languages/', views.list_potential_languages, name='list-potential-languages'),
]

ulpa/users/forms.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django import forms

from .models import User


class UserForm(forms.ModelForm):

    class Meta:
        # Set this form to use the User model.
        model = User

        # Constrain the UserForm to just these fields.
        fields = ("first_name", "last_name")

ulpa/core/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.shortcuts import render, redirect

from ulpa.core.forms import LanguageSearchForm, ContactForm, URLCheckForm
from ulpa.core.emails import contact_form_sent_handler
from ulpa.languages.models import Language, LanguageCategory
from ulpa.subjects.models import check_url as check_subject_urls
from ulpa.universities.models import University, check_url as check_university_urls
from ulpa.users.models import User

def setup(request):
    """
    Performs initial site setup
    """
    existing_admin_users = User.objects.filter(is_superuser=True)

    if not existing_admin_users:
        user = User(username='admin', email='evan.brumley@wspdigital.com')

        user.set_password('123')
        
        user.is_superuser = True
        user.is_staff = True
        
        user.save()
    else:
        user = None

    context = {
        'user': user,
    }

    return redirect('core:home')


def force_500(request):
    """
    For testing exception handling
    """
    if request.user.is_superuser:
        raise Exception("Test Exception")
    else:
        return redirect('core:home')


def google_verification(request):
    """
    For Googe Seach Console integration
    """
    template = "google_verification.html"

    context = {
    }

    if request.user.is_superuser:
        return render(request, template, context)
    else:
        return redirect('core:home')


def home(request):

    template = "core/home.html"

    context = {
    }

    return render(request, template, context)


def about(request):

    template = "core/about.html"

    context = {
    }

    return render(request, template, context)


def contact(request):

    template = "core/contact.html"

    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            contact_form_sent_handler(form)
            messages.success(request, "Message sent successfully")
            return redirect('core:home')
            # except Exception, e:
            #     messages.error(request, "An error occured and the message has not sent successfully. Please try again later. %s" % e)

    context = {
        'form': form,
    }

    return render(request, template, context)


def faq(request):

    template = "core/faq.html"

    context = {
    }

    return render(request, template, context)


def what_languages_can_i_study(request):

    template = "core/what_languages_can_i_study.html"

    languages = Language.objects.all()
    language_categories = LanguageCategory.objects.all().order_by('name')

    if request.method == 'POST':

        form = LanguageSearchForm(request.POST)

        if form.is_valid():
            language = form.cleaned_data.get('language')

    else:

        form = LanguageSearchForm()

    context = {
        'languages': languages,
        'language_categories': language_categories,
        'form': form,
    }

    return render(request, template, context)


def why_study_languages(request):

    template = "core/why_study_languages.html"

    languages = Language.objects.all()

    context = {
        'languages': languages,
    }

    return render(request, template, context)


def can_study_at_uni_other_than_own(request):

    template = "core/can_study_at_uni_other_than_own.html"

    # TODO - Needs updating to appropriate content!

    universities = University.objects.all()

    context = {
        'universities': universities,
    }

    return render(request, template, context)


def where_can_study_indigenous_languages(request):
    INDIGENOUS_LANGUAGES_SLUG = 'Australian Indigenous Languages'
    template = "core/where_can_study_indigenous_languages.html"

    universities = University.objects.all()
    indigenous_languages = Language.objects.filter(categories__name=INDIGENOUS_LANGUAGES_SLUG)

    context = {
        'indigenous_languages': indigenous_languages,
    }

    return render(request, template, context)


def health_check(request):
    template = "health_check.xml"

    status = 200

    context = {
        'status': "OK",
        'response_time': 1.1,  # TODO: Figure out wtf is going here
    }

    return render(request, template, context, status=status, content_type="text/xml")

@login_required
def url_check(request):
    template = "url_check.html"
    university_urls = ""
    subject_urls = ""
    results = {}

    if request.method == 'GET':
        form = URLCheckForm()
    else:
        university_urls = check_university_urls()
        subject_urls = check_subject_urls()
        form = URLCheckForm()

    if university_urls:
        results = {
            'universities': university_urls,
            'subjects': subject_urls,
        }

    context = {
        'form': form,
        'results': results,
    }

    return render(request, template, context)

@login_required
def url_check_results(request):
    template = "url_check_results.html"

    context = {

    }

    return render(request, template, context)


def sitemap(request):
    template = "sitemap.xml"

    context = {

    }

    return render(request, template, context)

ulpa/faqs/views.py
from django.shortcuts import render

from .models import FAQCategory


def faqs(request):
    """

    """
    template = "faqs/index.html"

    all_faqs = FAQCategory.objects.all()

    context = {
        'all_faqs': all_faqs,
    }

    return render(request, template, context)

ulpa/languages/views.py
import json
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse

from ulpa.universities.models import University
from ulpa.subjects.models import Subject

from .models import Language, LanguageCategory, LanguageBulkUpload
from .forms import LanguageSearchForm, LanguagesBulkUploadForm


@login_required
def languages_bulk_upload(request):
    """
    Initial page for bulk uploading Subjects within a XLSX file.
    If errors occur with file upload, deals with it here (not
    including parsing errors). Then passes the created bulk_upload
    to the confirm view below
    """
    template = "languages/bulk_upload.html"
    if request.method == 'POST':
        form = LanguagesBulkUploadForm(request.POST, request.FILES)
        if form.is_valid():
            bulk_upload = form.save(commit=False)
            bulk_upload.user = request.user

            bulk_upload.save()

            return redirect('languages:languages-confirm-bulk-upload', bulk_upload.pk)
        else:
            messages.error(request, "There was a problem with your submission,\
                                    please check the form below for errors and\
                                    try again")
    else:
        form = LanguagesBulkUploadForm()

    context = {
        'form': form,
    }

    return render(request, template, context)

@login_required
def languages_confirm_bulk_upload(request, bulk_upload_id):
    """
    Takes the bulk_upload created above and processes the data.
    Deals with errors if they occur, else, lets the user know
    how many subjects were successfully created.
    """

    template = "languages/confirm_bulk_upload.html"

    bulk_upload = get_object_or_404(LanguageBulkUpload, pk=bulk_upload_id)

    if not bulk_upload.is_pending:
        messages.error(request, "Sorry, the bulk upload you were accessing has\
                                 already been actioned. Please re-upload your\
                                 XLSX file.")

    results = bulk_upload.results

    if request.method == "POST":
        if 'submit_confirm' in request.POST and not bulk_upload.errors:
            languages = bulk_upload.process()

            added_languages = languages.get('languages')
            added_categories = languages.get('categories')

            messages.success(request, "%s languages created successfully. %s categories created successfully" % (len(added_languages), len(added_categories)))
            return redirect('core:home')

        elif 'submit_cancel' in request.POST:
            bulk_upload.cancel()
            messages.success(request, "Bulk upload cancelled")
            return redirect('languages-bulk-upload')

    context = {
        'bulk_upload': bulk_upload,
        'results': results,
    }

    return render(request, template, context)


def individual_language(request, *args, **kwargs):

    template = "languages/individual_language.html"

    language = kwargs.get('language')

    individual_language = get_object_or_404(Language, slug__iexact=language)
    subject_universities = Subject.objects.filter(language__slug=language).values_list('university', flat=True).distinct()
    universities_with_language = University.objects.filter(pk__in=subject_universities)

    context = {
        'universities_with_language': universities_with_language,
        'individual_language': individual_language,
    }

    return render(request, template, context)


def category_language(request, *args, **kwargs):

    template = "languages/category_language.html"

    category = kwargs.get('category')

    category_language = get_object_or_404(LanguageCategory, slug__iexact=category)
    individual_languages = Language.objects.filter(categories=category_language)

    context = {
        'category_language': category_language,
        'individual_languages': individual_languages,
    }

    return render(request, template, context)


def language_search(request, *args, **kwargs):

    template = "languages/language_search.html"

    state_choices = Subject.STATE_CHOICES
    states = []
    all_subjects = Subject.objects.all()

    for state in state_choices:
        universities = University.objects.filter(subjects__state=state[0]).distinct()
        states.append((state[0], universities))

    states.sort()
    form = LanguageSearchForm(request.GET or None)

    if form.is_valid():

        form = LanguageSearchForm(request.GET)

    context = {
        'form': form,
        'states': states,
    }

    return render(request, template, context)

def list_potential_subjects(request):
    response_subject = {}
    language_query = []
    all_subjects = Subject.objects.all()
    for var in request.GET:
        languageselected = request.GET.get(var)
        found_subjects = all_subjects.filter(language__name = languageselected)
        response_subject[languageselected] = len(found_subjects)

    return JsonResponse(response_subject, safe=False)


def list_universities(request):
    language_query = []
    response_universities = {}
    all_subjects = Subject.objects.all()
    state_choices = Subject.STATE_CHOICES
    states = []
    response_subjects = {}
    for var in request.GET:
        language = request.GET.get(var)
        language_query.append(language)
      
    available_subjects = Subject.objects.filter(language__name__in=language_query).select_related('university')
    
    for subject in available_subjects:
        if subject.state in response_universities:
            if subject.university.name in response_universities[subject.state]:
                pass
            else:
                response_universities[subject.state] += [subject.university.name]
        else:
            response_universities[subject.state] = [subject.university.name]

    for state in response_universities:
       for university in response_universities[state]:

           found_subjects = all_subjects.filter(language__name__in=language_query, university__name = university)
           if state in response_subjects:
              response_subjects[state] +=[(university,len(found_subjects))]
           else:
              response_subjects[state] = [(university,len(found_subjects))]

    return JsonResponse(response_subjects, safe=False)

ulpa/templates/core/about.html
{% extends "base.html" %}
{% load markdown_deux_tags %}
{% load staticfiles i18n %}

{% block title %}
    About ULPA
{% endblock title %}

{% block nav %}
    {% include "includes/nav.html" with active_tab='about' %}
{% endblock %}

{% block scrollspy %}data-spy="scroll" data-target="#about-nav"{% endblock %}

{% block content %}

    <div class="content">
        <div class="row about">

            <div class="col-xs-12">
                {{ site_configuration.about_page_heading|default:"<< about_page_heading >>"|markdown}}
            </div>
            <div class="col-xs-12 visible-xs visible-sm table-of-contents nav" id="contents">

            </div>
            <div class="col-xs-12 col-md-9">
                {{ site_configuration.about_page_content|default:"<< about_page_content >>"|markdown}}
            </div>

            <div id="about-nav" class="col-md-3">
                <ul id="nav" class="nav hidden-xs hidden-sm affix-top" data-spy="affix">
			    </ul>
		    </div>
        </div>

    </div>

{% endblock %}

{% block extra_scripts %}

    <script src="{% static 'js/about.js' %}"></script>
{% endblock extra_scripts %}

ulpa/templates/core/can_study_at_uni_other_than_own.html
{% extends "nav_base.html" %}
{% load markdown_deux_tags %}

{% block title %}
    Can I study at a university other than my own?
{% endblock title %}

{% block content %}


<div class="content">
    <div class="other-uni row">    
        
        <div class="col-xs-12 col-md-7">
        {{ site_configuration.other_university_heading|default:"<< other_university_page_heading >>"|markdown}}
        </div>

        <div class="col-xs-12">
            <div class="row">
                <div class="col-xs-12 col-md-8">
                    {{ site_configuration.other_university_content|default:"<< other_university_page_content >>"|markdown}}
                </div>
                
                <div class="col-xs-12 col-md-4">
                    <ul id="nav" class="nav hidden-xs hidden-sm">
                        <li>
                            <h5>Cross-Institutional Enrolment Policies</h5>
                        </li>
                        {% for university in universities %}
                            <li class="">
                                <a href="{{university.cross_institutional_url}}" target="_blank" onclick="trackOutboundLink({{university.cross_institutional_url}}); return false;">
                                    {{ university.name }}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-xs-12 visible-xs visible-sm">
            <ul id="nav" class="nav">
                <li>
                    <h5>Cross-Institutional Enrolment Policies</h5>
                </li>
                {% for university in universities %}
                    <li class="">
                        <a href="{{university.cross_institutional_url}}" target="_blank" onclick="trackOutboundLink({{university.cross_institutional_url}}); return false;">
                            {{ university.name }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

{% endblock %}

ulpa/templates/core/home.html
{% extends "home_base.html" %}

{% block title %}ULPA Home{% endblock %}
{% load markdown_deux_tags %}

{% block nav %}
    {% include "includes/nav.html" with active_tab='home' %}
{% endblock %}

{% block search_div %}
        
        <div class="row">
            <div class="home-page-heading col-xs-10  col-sm-5 col-xs-offset-1 col-sm-offset-0 col-md-offset-1">
                <h1>Do you want to study a language at university?</h1>
            </div>
            <div class="search-by-buttons hidden-xs col-sm-7 col-md-5 col-md-offset-1">
                <ul>
                    <li class="list-unstyled">
                        <a class="btn btn-search-by" href="{% url 'languages:language-search' %}">SEARCH BY LANGUAGE <div class="search-arrow "></div></a>
                    </li>
                    <li class="list-unstyled">
                        <a class="btn btn-search-by" href="{% url 'universities:university-search' %}">SEARCH BY UNIVERSITY <div class="search-arrow "></div></a>
                    </li>
                </ul>
            </div>
            <div class="search-by-buttons visible-xs-block col-xs-12">
                <li class="list-unstyled">
                    <a class="btn btn-search-by" href="{% url 'languages:language-search' %}">SEARCH BY LANGUAGE</a>
                </li>
                <li class="list-unstyled">
                    <a class="btn btn-search-by" href="{% url 'universities:university-search' %}">SEARCH BY UNIVERSITY</a>
                </li>
            </div>
        </div>

{% endblock search_div %}

{% block learn_more_div %}

        <div class="row">
            <div class="col-sm-3">
                <div class="row">
                    <a href="{% url 'core:why-study-languages' %}">
                        <div class="why-study-logo"></div>
                    </a>
                    <p class="learn-more-text text-center">
                        Why study languages?
                    </p>
                    <div  class="col-sm-8 col-sm-offset-2 hidden-xs ">
                        <a class="btn btn-ulpa btn-default" href="{% url 'core:why-study-languages' %}">LEARN MORE</a>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="row">
                    <a href="{% url 'core:where-can-study-indigenous-languages' %}">
                        <div class="indigenous-logo"></div>
                    </a>
                    <p class="learn-more-text text-center">
                        Where can I study an Australian Indigenous language?
                    </p>
                    <div  class="col-sm-8 col-sm-offset-2 hidden-xs">
                        <a class="btn btn-ulpa btn-default" href="{% url 'core:where-can-study-indigenous-languages' %}">LEARN MORE</a>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="row">
                    <a href="{% url 'core:can-study-at-university-other-than-own' %}">
                        <div class="other-university-logo"></div>
                    </a>
                    <p class="learn-more-text  text-center">
                        Can I study a language taught at a university other than my own?
                    </p>
                    <div class="col-sm-8 col-sm-offset-2 hidden-xs">
                        <a class="btn btn-ulpa btn-default" href="{% url 'core:can-study-at-university-other-than-own' %}">LEARN MORE</a>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="row">
                    <a href="{% url 'faqs:faqs' %}">
                        <div class="faq-logo"></div>
                    </a>
                    <p class="learn-more-text text-center">
                        Have another question on languages? Check out our FAQ section.
                    </p>
                    <div  class="col-sm-8 col-sm-offset-2 hidden-xs">
                        <a class="btn btn-ulpa btn-default" href="{% url 'faqs:faqs' %}">LEARN MORE</a>
                    </div>
                </div>
            </div>
        </div>


{% endblock learn_more_div %}

{% block what_languages_div %}
<div class="row">
    <div class="col-sm-5 col-sm-offset-7">
        <h1>What languages can I study?</h1>
    </div>
    <div class="col-sm-5 col-md-3 col-sm-offset-7">
        <a class="btn btn-search-by" href="{% url 'core:what-languages-can-i-study' %}">FIND OUT MORE<div class="search-arrow "></div></a>
    </div>
</div>
{% endblock what_languages_div %}

ulpa/templates/core/what_languages_can_i_study.html
{% extends "nav_base.html" %}
{% load markdown_deux_tags %}

{% block title %}
    What languages can I study?
{% endblock title %}

{% block content %}

<div class="row what-languages">

    <h1 class="col-xs-12">WHAT LANGUAGES CAN I STUDY?</h1>
    <div class="col-xs-12 col-sm-8">
        <div class="col-xs-12">
            {{ site_configuration.what_languages_can_study_content|default:"<< what_languages_can_study_content >>"|markdown}}
        </div>
    </div>

    <div class="col-sm-4">
        <ul id="nav" class="nav hidden-xs">
            <li>
                <h5>Languages currently on offer</h5>
            </li>
            {% for language_category in language_categories %}
                <li class="">
                    <a href="{% url 'languages:category-language' language_category.slug %}">
                        {{ language_category.name }}
                    </a>
                    <ul class="nav">
                        {% for language in language_category.languages.all %}
                            <li class="sub-menu ">
                                <a href="{% url 'languages:individual-language' language.slug %}">
                                    {{ language }}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="col-xs-12">
        <ul id="nav" class="nav visible-xs visible-sm">
            <li>
                <h5>Languages currently on offer</h5>
            </li>
            {% for language_category in language_categories %}
                <li class="">
                    <a href="{% url 'languages:category-language' language_category.slug %}">
                        {{ language_category.name }}
                    </a>
                    <ul class="nav">
                        {% for language in language_category.languages.all %}
                            <li class="sub-menu ">
                                <a href="{% url 'languages:individual-language' language.slug %}">
                                    {{ language }}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </li>
            {% endfor %}
        </ul>
    </div>
            <div class="search-by-buttons hidden-xs hidden-sm col-sm-12">
            <div class="col-xs-6">
                <a class="btn btn-search-by" href="{% url 'languages:language-search' %}">SEARCH BY LANGUAGE</a>
            </div>
            <div class="col-xs-6">
                <a class="btn btn-search-by" href="{% url 'universities:university-search' %}">SEARCH BY UNIVERSITY</a>
            </div>
        </div>
        <div class="search-by-buttons visible-xs-block visible-sm-block row">
            <li class="list-unstyled col-xs-12">
                <a class="btn btn-search-by" href="{% url 'languages:language-search' %}">SEARCH BY LANGUAGE <div class="search-arrow "></div></a>
            </li>
            <li class="list-unstyled col-xs-12">
                <a class="btn btn-search-by" href="{% url 'universities:university-search' %}">SEARCH BY UNIVERSITY <div class="search-arrow "></div></a>
            </li>
        </div>
</div>
    
{% endblock %}

ulpa/templates/core/where_can_study_indigenous_languages.html
{% extends "base.html" %}
{% load markdown_deux_tags %}
{% load staticfiles i18n %}

{% block title %}
    Where can I study indigenous languages?
{% endblock title %}


{% block nav %}
    {% include "includes/nav.html" with active_tab='none' %}
{% endblock %}

{% block scrollspy %}data-spy="scroll" data-target="#indigenous-languages"{% endblock %}

{% block content %}
    <div class="content">
        <div class="indigenous-languages row">
            <div class="col-xs-12">
                {{ site_configuration.where_can_study_indigenous_languages_heading|default:"<< indigenous_page_heading >>"|markdown}}
            </div>
            <div class="col-xs-12 visible-xs visible-sm table-of-contents nav" id="contents">
            </div>
            <div class="col-xs-12 col-md-9">
                {{ site_configuration.where_can_study_indigenous_languages_content|default:"<< indigenous_page_content >>"|markdown}}
            </div>
            <div id="why-study-nav" class="col-md-3">
                <ul id="nav" class="nav hidden-xs hidden-sm affix-top" data-spy="affix">
                </ul>
            </div>
            <div class="search-by-buttons col-xs-12 col-md-6 col-lg-4">
                <a class="btn btn-search-by" href="{% url 'subjects:subject-search-results' %}?{% for indigenous_language in indigenous_languages %}language={{indigenous_language.name}}&{% endfor %}">Show me what I can study</a>
            </div>

        </div>
    </div>

{% endblock %}

{% block extra_scripts %}
    <script src="{% static 'js/indigenous-languages.js' %}"></script>
{% endblock extra_scripts %}